/**
 * generated by Xtext 2.23.0
 */
package fr.n7.xtext.game.impl;

import fr.n7.xtext.game.Dialogue;
import fr.n7.xtext.game.GamePackage;
import fr.n7.xtext.game.Lieu;
import fr.n7.xtext.game.PNJ;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PNJ</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.xtext.game.impl.PNJImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.xtext.game.impl.PNJImpl#getLieu <em>Lieu</em>}</li>
 *   <li>{@link fr.n7.xtext.game.impl.PNJImpl#getDialogue <em>Dialogue</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PNJImpl extends ConditionnelImpl implements PNJ
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getLieu() <em>Lieu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLieu()
   * @generated
   * @ordered
   */
  protected Lieu lieu;

  /**
   * The cached value of the '{@link #getDialogue() <em>Dialogue</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDialogue()
   * @generated
   * @ordered
   */
  protected EList<Dialogue> dialogue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PNJImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.PNJ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.PNJ__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu getLieu()
  {
    if (lieu != null && lieu.eIsProxy())
    {
      InternalEObject oldLieu = (InternalEObject)lieu;
      lieu = (Lieu)eResolveProxy(oldLieu);
      if (lieu != oldLieu)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GamePackage.PNJ__LIEU, oldLieu, lieu));
      }
    }
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lieu basicGetLieu()
  {
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLieu(Lieu newLieu)
  {
    Lieu oldLieu = lieu;
    lieu = newLieu;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.PNJ__LIEU, oldLieu, lieu));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Dialogue> getDialogue()
  {
    if (dialogue == null)
    {
      dialogue = new EObjectContainmentEList<Dialogue>(Dialogue.class, this, GamePackage.PNJ__DIALOGUE);
    }
    return dialogue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.PNJ__DIALOGUE:
        return ((InternalEList<?>)getDialogue()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.PNJ__NAME:
        return getName();
      case GamePackage.PNJ__LIEU:
        if (resolve) return getLieu();
        return basicGetLieu();
      case GamePackage.PNJ__DIALOGUE:
        return getDialogue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.PNJ__NAME:
        setName((String)newValue);
        return;
      case GamePackage.PNJ__LIEU:
        setLieu((Lieu)newValue);
        return;
      case GamePackage.PNJ__DIALOGUE:
        getDialogue().clear();
        getDialogue().addAll((Collection<? extends Dialogue>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.PNJ__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GamePackage.PNJ__LIEU:
        setLieu((Lieu)null);
        return;
      case GamePackage.PNJ__DIALOGUE:
        getDialogue().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.PNJ__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GamePackage.PNJ__LIEU:
        return lieu != null;
      case GamePackage.PNJ__DIALOGUE:
        return dialogue != null && !dialogue.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PNJImpl
