/*
 * generated by Xtext 2.23.0
 */
package fr.n7.xtext.serializer;

import com.google.inject.Inject;
import fr.n7.xtext.services.GameGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class GameSyntacticSequencer extends AbstractSyntacticSequencer {

	protected GameGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Action___DonneKeyword_2_0_LeftParenthesisKeyword_2_1_RightParenthesisKeyword_2_4__q;
	protected AbstractElementAlias match_Lieu___ContientKeyword_3_0_RightParenthesisKeyword_3_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (GameGrammarAccess) access;
		match_Action___DonneKeyword_2_0_LeftParenthesisKeyword_2_1_RightParenthesisKeyword_2_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getActionAccess().getDonneKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getActionAccess().getLeftParenthesisKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getActionAccess().getRightParenthesisKeyword_2_4()));
		match_Lieu___ContientKeyword_3_0_RightParenthesisKeyword_3_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLieuAccess().getContientKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getLieuAccess().getRightParenthesisKeyword_3_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Action___DonneKeyword_2_0_LeftParenthesisKeyword_2_1_RightParenthesisKeyword_2_4__q.equals(syntax))
				emit_Action___DonneKeyword_2_0_LeftParenthesisKeyword_2_1_RightParenthesisKeyword_2_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Lieu___ContientKeyword_3_0_RightParenthesisKeyword_3_4__q.equals(syntax))
				emit_Lieu___ContientKeyword_3_0_RightParenthesisKeyword_3_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('donne' '(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) (rule end)
	 *     objetsConsommes+=ObjetTenu (ambiguity) (rule end)
	 */
	protected void emit_Action___DonneKeyword_2_0_LeftParenthesisKeyword_2_1_RightParenthesisKeyword_2_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('contient (' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=typePlace (ambiguity) (rule end)
	 */
	protected void emit_Lieu___ContientKeyword_3_0_RightParenthesisKeyword_3_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
