/**
 * generated by Xtext 2.23.0
 */
package fr.n7.xtext.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.xtext.game.Lieu#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.xtext.game.Lieu#getType <em>Type</em>}</li>
 *   <li>{@link fr.n7.xtext.game.Lieu#getPnjs <em>Pnjs</em>}</li>
 *   <li>{@link fr.n7.xtext.game.Lieu#getObjets <em>Objets</em>}</li>
 *   <li>{@link fr.n7.xtext.game.Lieu#getConnaissances <em>Connaissances</em>}</li>
 * </ul>
 *
 * @see fr.n7.xtext.game.GamePackage#getLieu()
 * @model
 * @generated
 */
public interface Lieu extends JeuElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.xtext.game.GamePackage#getLieu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.xtext.game.Lieu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.xtext.game.typePlace}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see fr.n7.xtext.game.typePlace
   * @see #setType(typePlace)
   * @see fr.n7.xtext.game.GamePackage#getLieu_Type()
   * @model
   * @generated
   */
  typePlace getType();

  /**
   * Sets the value of the '{@link fr.n7.xtext.game.Lieu#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see fr.n7.xtext.game.typePlace
   * @see #getType()
   * @generated
   */
  void setType(typePlace value);

  /**
   * Returns the value of the '<em><b>Pnjs</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.xtext.game.PNJ}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pnjs</em>' containment reference list.
   * @see fr.n7.xtext.game.GamePackage#getLieu_Pnjs()
   * @model containment="true"
   * @generated
   */
  EList<PNJ> getPnjs();

  /**
   * Returns the value of the '<em><b>Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.xtext.game.ObjetTenu}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objets</em>' containment reference list.
   * @see fr.n7.xtext.game.GamePackage#getLieu_Objets()
   * @model containment="true"
   * @generated
   */
  EList<ObjetTenu> getObjets();

  /**
   * Returns the value of the '<em><b>Connaissances</b></em>' reference list.
   * The list contents are of type {@link fr.n7.xtext.game.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connaissances</em>' reference list.
   * @see fr.n7.xtext.game.GamePackage#getLieu_Connaissances()
   * @model
   * @generated
   */
  EList<Connaissance> getConnaissances();

} // Lieu
