/*
 * generated by Xtext 2.23.0
 */
package fr.n7.xtext.ui.tests;

import com.google.inject.Injector;
import fr.n7.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GameUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.n7.xtext.Game");
	}

}
