/*
 * generated by Xtext 2.23.0
 */
package fr.n7.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.n7.xtext.ide.contentassist.antlr.internal.InternalGameParser;
import fr.n7.xtext.services.GameGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GameParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GameGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GameGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getConditionAccess().getAlternatives_5(), "rule__Condition__Alternatives_5");
			builder.put(grammarAccess.getConditionnelAccess().getAlternatives(), "rule__Conditionnel__Alternatives");
			builder.put(grammarAccess.getJeuElementAccess().getAlternatives(), "rule__JeuElement__Alternatives");
			builder.put(grammarAccess.getTypePlaceAccess().getAlternatives(), "rule__TypePlace__Alternatives");
			builder.put(grammarAccess.getJeuAccess().getGroup(), "rule__Jeu__Group__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup(), "rule__Connaissance__Group__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup_1(), "rule__Connaissance__Group_1__0");
			builder.put(grammarAccess.getConnaissanceAccess().getGroup_1_3(), "rule__Connaissance__Group_1_3__0");
			builder.put(grammarAccess.getObjetAccess().getGroup(), "rule__Objet__Group__0");
			builder.put(grammarAccess.getObjetTenuAccess().getGroup(), "rule__ObjetTenu__Group__0");
			builder.put(grammarAccess.getObjetTenuAccess().getGroup_3(), "rule__ObjetTenu__Group_3__0");
			builder.put(grammarAccess.getObjetTenuAccess().getGroup_3_3(), "rule__ObjetTenu__Group_3_3__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_5_0(), "rule__Condition__Group_5_0__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_5_1(), "rule__Condition__Group_5_1__0");
			builder.put(grammarAccess.getPNJAccess().getGroup(), "rule__PNJ__Group__0");
			builder.put(grammarAccess.getPNJAccess().getGroup_9(), "rule__PNJ__Group_9__0");
			builder.put(grammarAccess.getPNJAccess().getGroup_9_3(), "rule__PNJ__Group_9_3__0");
			builder.put(grammarAccess.getLieuAccess().getGroup(), "rule__Lieu__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3(), "rule__Lieu__Group_3__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3_1(), "rule__Lieu__Group_3_1__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3_1_2(), "rule__Lieu__Group_3_1_2__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3_2(), "rule__Lieu__Group_3_2__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3_2_2(), "rule__Lieu__Group_3_2_2__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3_3(), "rule__Lieu__Group_3_3__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_3_3_2(), "rule__Lieu__Group_3_3_2__0");
			builder.put(grammarAccess.getDialogueAccess().getGroup(), "rule__Dialogue__Group__0");
			builder.put(grammarAccess.getDialogueAccess().getGroup_5(), "rule__Dialogue__Group_5__0");
			builder.put(grammarAccess.getDialogueAccess().getGroup_5_3(), "rule__Dialogue__Group_5_3__0");
			builder.put(grammarAccess.getChoixAccess().getGroup(), "rule__Choix__Group__0");
			builder.put(grammarAccess.getChoixAccess().getGroup_1(), "rule__Choix__Group_1__0");
			builder.put(grammarAccess.getChoixAccess().getGroup_1_2(), "rule__Choix__Group_1_2__0");
			builder.put(grammarAccess.getChoixAccess().getGroup_2(), "rule__Choix__Group_2__0");
			builder.put(grammarAccess.getChoixAccess().getGroup_2_3(), "rule__Choix__Group_2_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_1(), "rule__Action__Group_1__0");
			builder.put(grammarAccess.getActionAccess().getGroup_1_2(), "rule__Action__Group_1_2__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2(), "rule__Action__Group_2__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2_2(), "rule__Action__Group_2_2__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2_2_2(), "rule__Action__Group_2_2_2__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2_3(), "rule__Action__Group_2_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2_3_2(), "rule__Action__Group_2_3_2__0");
			builder.put(grammarAccess.getCheminAccess().getGroup(), "rule__Chemin__Group__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_4(), "rule__Chemin__Group_4__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_4_2(), "rule__Chemin__Group_4_2__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_5(), "rule__Chemin__Group_5__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_5_3(), "rule__Chemin__Group_5_3__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_6(), "rule__Chemin__Group_6__0");
			builder.put(grammarAccess.getCheminAccess().getGroup_6_3(), "rule__Chemin__Group_6_3__0");
			builder.put(grammarAccess.getJoueurAccess().getGroup(), "rule__Joueur__Group__0");
			builder.put(grammarAccess.getJoueurAccess().getGroup_8(), "rule__Joueur__Group_8__0");
			builder.put(grammarAccess.getJoueurAccess().getGroup_8_3(), "rule__Joueur__Group_8_3__0");
			builder.put(grammarAccess.getJoueurAccess().getGroup_9(), "rule__Joueur__Group_9__0");
			builder.put(grammarAccess.getJoueurAccess().getGroup_9_4(), "rule__Joueur__Group_9_4__0");
			builder.put(grammarAccess.getJeuAccess().getNameAssignment_1(), "rule__Jeu__NameAssignment_1");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_4(), "rule__Jeu__JeuElementsAssignment_4");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_8(), "rule__Jeu__JeuElementsAssignment_8");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_12(), "rule__Jeu__JeuElementsAssignment_12");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_16(), "rule__Jeu__JeuElementsAssignment_16");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_20(), "rule__Jeu__JeuElementsAssignment_20");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_24(), "rule__Jeu__JeuElementsAssignment_24");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_28(), "rule__Jeu__JeuElementsAssignment_28");
			builder.put(grammarAccess.getJeuAccess().getJeuElementsAssignment_32(), "rule__Jeu__JeuElementsAssignment_32");
			builder.put(grammarAccess.getConnaissanceAccess().getNameAssignment_0(), "rule__Connaissance__NameAssignment_0");
			builder.put(grammarAccess.getConnaissanceAccess().getConditionsVisibiliteAssignment_1_2(), "rule__Connaissance__ConditionsVisibiliteAssignment_1_2");
			builder.put(grammarAccess.getConnaissanceAccess().getConditionsVisibiliteAssignment_1_3_1(), "rule__Connaissance__ConditionsVisibiliteAssignment_1_3_1");
			builder.put(grammarAccess.getObjetAccess().getNameAssignment_1(), "rule__Objet__NameAssignment_1");
			builder.put(grammarAccess.getObjetAccess().getTailleAssignment_3(), "rule__Objet__TailleAssignment_3");
			builder.put(grammarAccess.getObjetAccess().getQuantiteAssignment_6(), "rule__Objet__QuantiteAssignment_6");
			builder.put(grammarAccess.getObjetTenuAccess().getObjetAssignment_0(), "rule__ObjetTenu__ObjetAssignment_0");
			builder.put(grammarAccess.getObjetTenuAccess().getQuantiteAssignment_2(), "rule__ObjetTenu__QuantiteAssignment_2");
			builder.put(grammarAccess.getObjetTenuAccess().getConditionsVisibiliteAssignment_3_2(), "rule__ObjetTenu__ConditionsVisibiliteAssignment_3_2");
			builder.put(grammarAccess.getObjetTenuAccess().getConditionsVisibiliteAssignment_3_3_1(), "rule__ObjetTenu__ConditionsVisibiliteAssignment_3_3_1");
			builder.put(grammarAccess.getConditionAccess().getNameAssignment_0(), "rule__Condition__NameAssignment_0");
			builder.put(grammarAccess.getConditionAccess().getNegationAssignment_5_0_0(), "rule__Condition__NegationAssignment_5_0_0");
			builder.put(grammarAccess.getConditionAccess().getObjetAssignment_5_0_2(), "rule__Condition__ObjetAssignment_5_0_2");
			builder.put(grammarAccess.getConditionAccess().getNegationAssignment_5_1_0(), "rule__Condition__NegationAssignment_5_1_0");
			builder.put(grammarAccess.getConditionAccess().getConnaissanceAssignment_5_1_2(), "rule__Condition__ConnaissanceAssignment_5_1_2");
			builder.put(grammarAccess.getPNJAccess().getNameAssignment_0(), "rule__PNJ__NameAssignment_0");
			builder.put(grammarAccess.getPNJAccess().getLieuAssignment_3(), "rule__PNJ__LieuAssignment_3");
			builder.put(grammarAccess.getPNJAccess().getDialogueAssignment_7(), "rule__PNJ__DialogueAssignment_7");
			builder.put(grammarAccess.getPNJAccess().getConditionsVisibiliteAssignment_9_2(), "rule__PNJ__ConditionsVisibiliteAssignment_9_2");
			builder.put(grammarAccess.getPNJAccess().getConditionsVisibiliteAssignment_9_3_1(), "rule__PNJ__ConditionsVisibiliteAssignment_9_3_1");
			builder.put(grammarAccess.getLieuAccess().getNameAssignment_0(), "rule__Lieu__NameAssignment_0");
			builder.put(grammarAccess.getLieuAccess().getTypeAssignment_2(), "rule__Lieu__TypeAssignment_2");
			builder.put(grammarAccess.getLieuAccess().getPnjsAssignment_3_1_1(), "rule__Lieu__PnjsAssignment_3_1_1");
			builder.put(grammarAccess.getLieuAccess().getPnjsAssignment_3_1_2_1(), "rule__Lieu__PnjsAssignment_3_1_2_1");
			builder.put(grammarAccess.getLieuAccess().getObjetsAssignment_3_2_1(), "rule__Lieu__ObjetsAssignment_3_2_1");
			builder.put(grammarAccess.getLieuAccess().getObjetsAssignment_3_2_2_1(), "rule__Lieu__ObjetsAssignment_3_2_2_1");
			builder.put(grammarAccess.getLieuAccess().getConnaissancesAssignment_3_3_1(), "rule__Lieu__ConnaissancesAssignment_3_3_1");
			builder.put(grammarAccess.getLieuAccess().getConnaissancesAssignment_3_3_2_1(), "rule__Lieu__ConnaissancesAssignment_3_3_2_1");
			builder.put(grammarAccess.getDialogueAccess().getTexteAssignment_0(), "rule__Dialogue__TexteAssignment_0");
			builder.put(grammarAccess.getDialogueAccess().getReponsesAssignment_3(), "rule__Dialogue__ReponsesAssignment_3");
			builder.put(grammarAccess.getDialogueAccess().getConditionsVisibiliteAssignment_5_2(), "rule__Dialogue__ConditionsVisibiliteAssignment_5_2");
			builder.put(grammarAccess.getDialogueAccess().getConditionsVisibiliteAssignment_5_3_1(), "rule__Dialogue__ConditionsVisibiliteAssignment_5_3_1");
			builder.put(grammarAccess.getChoixAccess().getTexteAssignment_0(), "rule__Choix__TexteAssignment_0");
			builder.put(grammarAccess.getChoixAccess().getActionsAssignment_1_1(), "rule__Choix__ActionsAssignment_1_1");
			builder.put(grammarAccess.getChoixAccess().getActionsAssignment_1_2_1(), "rule__Choix__ActionsAssignment_1_2_1");
			builder.put(grammarAccess.getChoixAccess().getConditionsVisibiliteAssignment_2_2(), "rule__Choix__ConditionsVisibiliteAssignment_2_2");
			builder.put(grammarAccess.getChoixAccess().getConditionsVisibiliteAssignment_2_3_1(), "rule__Choix__ConditionsVisibiliteAssignment_2_3_1");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_0(), "rule__Action__NameAssignment_0");
			builder.put(grammarAccess.getActionAccess().getObjetsConsommesAssignment_1_1(), "rule__Action__ObjetsConsommesAssignment_1_1");
			builder.put(grammarAccess.getActionAccess().getObjetsConsommesAssignment_1_2_1(), "rule__Action__ObjetsConsommesAssignment_1_2_1");
			builder.put(grammarAccess.getActionAccess().getObjetDonnesAssignment_2_2_1(), "rule__Action__ObjetDonnesAssignment_2_2_1");
			builder.put(grammarAccess.getActionAccess().getObjetsDonnesAssignment_2_2_2_1(), "rule__Action__ObjetsDonnesAssignment_2_2_2_1");
			builder.put(grammarAccess.getActionAccess().getConnaissancesAssignment_2_3_1(), "rule__Action__ConnaissancesAssignment_2_3_1");
			builder.put(grammarAccess.getActionAccess().getConnaissancesAssignment_2_3_2_1(), "rule__Action__ConnaissancesAssignment_2_3_2_1");
			builder.put(grammarAccess.getCheminAccess().getLieu1Assignment_1(), "rule__Chemin__Lieu1Assignment_1");
			builder.put(grammarAccess.getCheminAccess().getLieu2Assignment_3(), "rule__Chemin__Lieu2Assignment_3");
			builder.put(grammarAccess.getCheminAccess().getActionsAssignment_4_1(), "rule__Chemin__ActionsAssignment_4_1");
			builder.put(grammarAccess.getCheminAccess().getActionsAssignment_4_2_1(), "rule__Chemin__ActionsAssignment_4_2_1");
			builder.put(grammarAccess.getCheminAccess().getConditionsOuvertureAssignment_5_2(), "rule__Chemin__ConditionsOuvertureAssignment_5_2");
			builder.put(grammarAccess.getCheminAccess().getConditionsOuvertureAssignment_5_3_1(), "rule__Chemin__ConditionsOuvertureAssignment_5_3_1");
			builder.put(grammarAccess.getCheminAccess().getConditionsVisibiliteAssignment_6_2(), "rule__Chemin__ConditionsVisibiliteAssignment_6_2");
			builder.put(grammarAccess.getCheminAccess().getConditionsVisibiliteAssignment_6_3_1(), "rule__Chemin__ConditionsVisibiliteAssignment_6_3_1");
			builder.put(grammarAccess.getJoueurAccess().getNameAssignment_0(), "rule__Joueur__NameAssignment_0");
			builder.put(grammarAccess.getJoueurAccess().getLieuAssignment_3(), "rule__Joueur__LieuAssignment_3");
			builder.put(grammarAccess.getJoueurAccess().getTailleAssignment_7(), "rule__Joueur__TailleAssignment_7");
			builder.put(grammarAccess.getJoueurAccess().getInventaireAssignment_8_2(), "rule__Joueur__InventaireAssignment_8_2");
			builder.put(grammarAccess.getJoueurAccess().getInventaireAssignment_8_3_1(), "rule__Joueur__InventaireAssignment_8_3_1");
			builder.put(grammarAccess.getJoueurAccess().getConnaissancesAssignment_9_3(), "rule__Joueur__ConnaissancesAssignment_9_3");
			builder.put(grammarAccess.getJoueurAccess().getConnaissancesAssignment_9_4_1(), "rule__Joueur__ConnaissancesAssignment_9_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GameGrammarAccess grammarAccess;

	@Override
	protected InternalGameParser createParser() {
		InternalGameParser result = new InternalGameParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
