/*
 * generated by Xtext 2.23.0
 */
package fr.n7.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GameGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class JeuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Jeu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJeuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cConnaissancesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cJeuElementsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cJeuElementsConnaissanceParserRuleCall_4_0 = (RuleCall)cJeuElementsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cObjetsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cJeuElementsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cJeuElementsObjetParserRuleCall_8_0 = (RuleCall)cJeuElementsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cPNJsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cJeuElementsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cJeuElementsPNJParserRuleCall_12_0 = (RuleCall)cJeuElementsAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cActionsKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cLeftCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cJeuElementsAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cJeuElementsActionParserRuleCall_16_0 = (RuleCall)cJeuElementsAssignment_16.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cConditionsKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cLeftCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cJeuElementsAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cJeuElementsConditionParserRuleCall_20_0 = (RuleCall)cJeuElementsAssignment_20.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Keyword cLieuxKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Keyword cLeftCurlyBracketKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Assignment cJeuElementsAssignment_24 = (Assignment)cGroup.eContents().get(24);
		private final RuleCall cJeuElementsLieuParserRuleCall_24_0 = (RuleCall)cJeuElementsAssignment_24.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Keyword cCheminsKeyword_26 = (Keyword)cGroup.eContents().get(26);
		private final Keyword cLeftCurlyBracketKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Assignment cJeuElementsAssignment_28 = (Assignment)cGroup.eContents().get(28);
		private final RuleCall cJeuElementsCheminParserRuleCall_28_0 = (RuleCall)cJeuElementsAssignment_28.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Keyword cJoueurKeyword_30 = (Keyword)cGroup.eContents().get(30);
		private final Keyword cLeftCurlyBracketKeyword_31 = (Keyword)cGroup.eContents().get(31);
		private final Assignment cJeuElementsAssignment_32 = (Assignment)cGroup.eContents().get(32);
		private final RuleCall cJeuElementsJoueurParserRuleCall_32_0 = (RuleCall)cJeuElementsAssignment_32.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_33 = (Keyword)cGroup.eContents().get(33);
		
		//Jeu:
		//	'jeu' name=ID
		//	'Connaissances' '{'
		//	jeuElements+=Connaissance*
		//	'}'
		//	'Objets' '{'
		//	jeuElements+=Objet*
		//	'}'
		//	'PNJs' '{'
		//	jeuElements+=PNJ*
		//	'}'
		//	'Actions' '{'
		//	jeuElements+=Action*
		//	'}'
		//	'Conditions' '{'
		//	jeuElements+=Condition*
		//	'}'
		//	'Lieux' '{'
		//	jeuElements+=Lieu*
		//	'}'
		//	'Chemins' '{'
		//	jeuElements+=Chemin*
		//	'}'
		//	'Joueur' '{'
		//	jeuElements+=Joueur
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'jeu' name=ID 'Connaissances' '{' jeuElements+=Connaissance* '}' 'Objets' '{' jeuElements+=Objet* '}' 'PNJs' '{'
		//jeuElements+=PNJ* '}' 'Actions' '{' jeuElements+=Action* '}' 'Conditions' '{' jeuElements+=Condition* '}' 'Lieux' '{'
		//jeuElements+=Lieu* '}' 'Chemins' '{' jeuElements+=Chemin* '}' 'Joueur' '{' jeuElements+=Joueur '}'
		public Group getGroup() { return cGroup; }
		
		//'jeu'
		public Keyword getJeuKeyword_0() { return cJeuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'Connaissances'
		public Keyword getConnaissancesKeyword_2() { return cConnaissancesKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//jeuElements+=Connaissance*
		public Assignment getJeuElementsAssignment_4() { return cJeuElementsAssignment_4; }
		
		//Connaissance
		public RuleCall getJeuElementsConnaissanceParserRuleCall_4_0() { return cJeuElementsConnaissanceParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//'Objets'
		public Keyword getObjetsKeyword_6() { return cObjetsKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//jeuElements+=Objet*
		public Assignment getJeuElementsAssignment_8() { return cJeuElementsAssignment_8; }
		
		//Objet
		public RuleCall getJeuElementsObjetParserRuleCall_8_0() { return cJeuElementsObjetParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'PNJs'
		public Keyword getPNJsKeyword_10() { return cPNJsKeyword_10; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }
		
		//jeuElements+=PNJ*
		public Assignment getJeuElementsAssignment_12() { return cJeuElementsAssignment_12; }
		
		//PNJ
		public RuleCall getJeuElementsPNJParserRuleCall_12_0() { return cJeuElementsPNJParserRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'Actions'
		public Keyword getActionsKeyword_14() { return cActionsKeyword_14; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_15() { return cLeftCurlyBracketKeyword_15; }
		
		//jeuElements+=Action*
		public Assignment getJeuElementsAssignment_16() { return cJeuElementsAssignment_16; }
		
		//Action
		public RuleCall getJeuElementsActionParserRuleCall_16_0() { return cJeuElementsActionParserRuleCall_16_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
		
		//'Conditions'
		public Keyword getConditionsKeyword_18() { return cConditionsKeyword_18; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_19() { return cLeftCurlyBracketKeyword_19; }
		
		//jeuElements+=Condition*
		public Assignment getJeuElementsAssignment_20() { return cJeuElementsAssignment_20; }
		
		//Condition
		public RuleCall getJeuElementsConditionParserRuleCall_20_0() { return cJeuElementsConditionParserRuleCall_20_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_21() { return cRightCurlyBracketKeyword_21; }
		
		//'Lieux'
		public Keyword getLieuxKeyword_22() { return cLieuxKeyword_22; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_23() { return cLeftCurlyBracketKeyword_23; }
		
		//jeuElements+=Lieu*
		public Assignment getJeuElementsAssignment_24() { return cJeuElementsAssignment_24; }
		
		//Lieu
		public RuleCall getJeuElementsLieuParserRuleCall_24_0() { return cJeuElementsLieuParserRuleCall_24_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_25() { return cRightCurlyBracketKeyword_25; }
		
		//'Chemins'
		public Keyword getCheminsKeyword_26() { return cCheminsKeyword_26; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_27() { return cLeftCurlyBracketKeyword_27; }
		
		//jeuElements+=Chemin*
		public Assignment getJeuElementsAssignment_28() { return cJeuElementsAssignment_28; }
		
		//Chemin
		public RuleCall getJeuElementsCheminParserRuleCall_28_0() { return cJeuElementsCheminParserRuleCall_28_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_29() { return cRightCurlyBracketKeyword_29; }
		
		//'Joueur'
		public Keyword getJoueurKeyword_30() { return cJoueurKeyword_30; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_31() { return cLeftCurlyBracketKeyword_31; }
		
		//jeuElements+=Joueur
		public Assignment getJeuElementsAssignment_32() { return cJeuElementsAssignment_32; }
		
		//Joueur
		public RuleCall getJeuElementsJoueurParserRuleCall_32_0() { return cJeuElementsJoueurParserRuleCall_32_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_33() { return cRightCurlyBracketKeyword_33; }
	}
	public class ConnaissanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Connaissance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cVisibleKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cSiKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cConditionsVisibiliteAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_1_2_0 = (CrossReference)cConditionsVisibiliteAssignment_1_2.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_1_2_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_1_2_0.eContents().get(1);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cCommaKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_1_3_1_0 = (CrossReference)cConditionsVisibiliteAssignment_1_3_1.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_1_3_1_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_1_3_1_0.eContents().get(1);
		
		//Connaissance:
		//	name=ID ('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'visible'
		public Keyword getVisibleKeyword_1_0() { return cVisibleKeyword_1_0; }
		
		//'si'
		public Keyword getSiKeyword_1_1() { return cSiKeyword_1_1; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_1_2() { return cConditionsVisibiliteAssignment_1_2; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_1_2_0() { return cConditionsVisibiliteConditionCrossReference_1_2_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_1_2_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_1_2_0_1; }
		
		//(',' conditionsVisibilite+=[Condition])*
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//','
		public Keyword getCommaKeyword_1_3_0() { return cCommaKeyword_1_3_0; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_1_3_1() { return cConditionsVisibiliteAssignment_1_3_1; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_1_3_1_0() { return cConditionsVisibiliteConditionCrossReference_1_3_1_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_1_3_1_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_1_3_1_0_1; }
	}
	public class ObjetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Objet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTailleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTailleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTailleINTTerminalRuleCall_3_0 = (RuleCall)cTailleAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cAsteriskKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cQuantiteAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cQuantiteINTTerminalRuleCall_6_0 = (RuleCall)cQuantiteAssignment_6.eContents().get(0);
		
		//Objet:
		//	'(' name=ID 'taille' taille=INT ')' '*' quantite=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' name=ID 'taille' taille=INT ')' '*' quantite=INT
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'taille'
		public Keyword getTailleKeyword_2() { return cTailleKeyword_2; }
		
		//taille=INT
		public Assignment getTailleAssignment_3() { return cTailleAssignment_3; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_3_0() { return cTailleINTTerminalRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'*'
		public Keyword getAsteriskKeyword_5() { return cAsteriskKeyword_5; }
		
		//quantite=INT
		public Assignment getQuantiteAssignment_6() { return cQuantiteAssignment_6; }
		
		//INT
		public RuleCall getQuantiteINTTerminalRuleCall_6_0() { return cQuantiteINTTerminalRuleCall_6_0; }
	}
	public class ObjetTenuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.ObjetTenu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cObjetAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cObjetObjetCrossReference_0_0 = (CrossReference)cObjetAssignment_0.eContents().get(0);
		private final RuleCall cObjetObjetIDTerminalRuleCall_0_0_1 = (RuleCall)cObjetObjetCrossReference_0_0.eContents().get(1);
		private final Keyword cAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cQuantiteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cQuantiteINTTerminalRuleCall_2_0 = (RuleCall)cQuantiteAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVisibleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cSiKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cConditionsVisibiliteAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_3_2_0 = (CrossReference)cConditionsVisibiliteAssignment_3_2.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_3_2_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_3_3_1_0 = (CrossReference)cConditionsVisibiliteAssignment_3_3_1.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_3_3_1_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_3_3_1_0.eContents().get(1);
		
		//ObjetTenu:
		//	objet=[Objet] '*' quantite=INT ('visible' 'si' conditionsVisibilite+=[Condition] (','
		//	conditionsVisibilite+=[Condition])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//objet=[Objet] '*' quantite=INT ('visible' 'si' conditionsVisibilite+=[Condition] (','
		//conditionsVisibilite+=[Condition])*)?
		public Group getGroup() { return cGroup; }
		
		//objet=[Objet]
		public Assignment getObjetAssignment_0() { return cObjetAssignment_0; }
		
		//[Objet]
		public CrossReference getObjetObjetCrossReference_0_0() { return cObjetObjetCrossReference_0_0; }
		
		//ID
		public RuleCall getObjetObjetIDTerminalRuleCall_0_0_1() { return cObjetObjetIDTerminalRuleCall_0_0_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_1() { return cAsteriskKeyword_1; }
		
		//quantite=INT
		public Assignment getQuantiteAssignment_2() { return cQuantiteAssignment_2; }
		
		//INT
		public RuleCall getQuantiteINTTerminalRuleCall_2_0() { return cQuantiteINTTerminalRuleCall_2_0; }
		
		//('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'visible'
		public Keyword getVisibleKeyword_3_0() { return cVisibleKeyword_3_0; }
		
		//'si'
		public Keyword getSiKeyword_3_1() { return cSiKeyword_3_1; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_3_2() { return cConditionsVisibiliteAssignment_3_2; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_3_2_0() { return cConditionsVisibiliteConditionCrossReference_3_2_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_3_2_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_3_2_0_1; }
		
		//(',' conditionsVisibilite+=[Condition])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//','
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_3_3_1() { return cConditionsVisibiliteAssignment_3_3_1; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_3_3_1_0() { return cConditionsVisibiliteConditionCrossReference_3_3_1_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_3_3_1_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_3_3_1_0_1; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEstKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cJoueurKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPossedeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Group cGroup_5_0 = (Group)cAlternatives_5.eContents().get(0);
		private final Assignment cNegationAssignment_5_0_0 = (Assignment)cGroup_5_0.eContents().get(0);
		private final Keyword cNegationPasKeyword_5_0_0_0 = (Keyword)cNegationAssignment_5_0_0.eContents().get(0);
		private final Keyword cObjetKeyword_5_0_1 = (Keyword)cGroup_5_0.eContents().get(1);
		private final Assignment cObjetAssignment_5_0_2 = (Assignment)cGroup_5_0.eContents().get(2);
		private final RuleCall cObjetObjetTenuParserRuleCall_5_0_2_0 = (RuleCall)cObjetAssignment_5_0_2.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cAlternatives_5.eContents().get(1);
		private final Assignment cNegationAssignment_5_1_0 = (Assignment)cGroup_5_1.eContents().get(0);
		private final Keyword cNegationPasKeyword_5_1_0_0 = (Keyword)cNegationAssignment_5_1_0.eContents().get(0);
		private final Keyword cConnaissanceKeyword_5_1_1 = (Keyword)cGroup_5_1.eContents().get(1);
		private final Assignment cConnaissanceAssignment_5_1_2 = (Assignment)cGroup_5_1.eContents().get(2);
		private final CrossReference cConnaissanceConnaissanceCrossReference_5_1_2_0 = (CrossReference)cConnaissanceAssignment_5_1_2.eContents().get(0);
		private final RuleCall cConnaissanceConnaissanceIDTerminalRuleCall_5_1_2_0_1 = (RuleCall)cConnaissanceConnaissanceCrossReference_5_1_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Condition:
		//	name=ID 'est' 'joueur' 'possede' '(' (negation?='pas'? 'objet:' objet=ObjetTenu | negation?='pas'? 'connaissance:'
		//	connaissance=[Connaissance]) ')';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'est' 'joueur' 'possede' '(' (negation?='pas'? 'objet:' objet=ObjetTenu | negation?='pas'? 'connaissance:'
		//connaissance=[Connaissance]) ')'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'est'
		public Keyword getEstKeyword_1() { return cEstKeyword_1; }
		
		//'joueur'
		public Keyword getJoueurKeyword_2() { return cJoueurKeyword_2; }
		
		//'possede'
		public Keyword getPossedeKeyword_3() { return cPossedeKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//(negation?='pas'? 'objet:' objet=ObjetTenu | negation?='pas'? 'connaissance:' connaissance=[Connaissance])
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//negation?='pas'? 'objet:' objet=ObjetTenu
		public Group getGroup_5_0() { return cGroup_5_0; }
		
		//negation?='pas'?
		public Assignment getNegationAssignment_5_0_0() { return cNegationAssignment_5_0_0; }
		
		//'pas'
		public Keyword getNegationPasKeyword_5_0_0_0() { return cNegationPasKeyword_5_0_0_0; }
		
		//'objet:'
		public Keyword getObjetKeyword_5_0_1() { return cObjetKeyword_5_0_1; }
		
		//objet=ObjetTenu
		public Assignment getObjetAssignment_5_0_2() { return cObjetAssignment_5_0_2; }
		
		//ObjetTenu
		public RuleCall getObjetObjetTenuParserRuleCall_5_0_2_0() { return cObjetObjetTenuParserRuleCall_5_0_2_0; }
		
		//negation?='pas'? 'connaissance:' connaissance=[Connaissance]
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//negation?='pas'?
		public Assignment getNegationAssignment_5_1_0() { return cNegationAssignment_5_1_0; }
		
		//'pas'
		public Keyword getNegationPasKeyword_5_1_0_0() { return cNegationPasKeyword_5_1_0_0; }
		
		//'connaissance:'
		public Keyword getConnaissanceKeyword_5_1_1() { return cConnaissanceKeyword_5_1_1; }
		
		//connaissance=[Connaissance]
		public Assignment getConnaissanceAssignment_5_1_2() { return cConnaissanceAssignment_5_1_2; }
		
		//[Connaissance]
		public CrossReference getConnaissanceConnaissanceCrossReference_5_1_2_0() { return cConnaissanceConnaissanceCrossReference_5_1_2_0; }
		
		//ID
		public RuleCall getConnaissanceConnaissanceIDTerminalRuleCall_5_1_2_0_1() { return cConnaissanceConnaissanceIDTerminalRuleCall_5_1_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class PNJElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.PNJ");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cSitueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEnKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLieuAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cLieuLieuCrossReference_3_0 = (CrossReference)cLieuAssignment_3.eContents().get(0);
		private final RuleCall cLieuLieuIDTerminalRuleCall_3_0_1 = (RuleCall)cLieuLieuCrossReference_3_0.eContents().get(1);
		private final Keyword cEtKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDialogueKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDialogueAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDialogueDialogueParserRuleCall_7_0 = (RuleCall)cDialogueAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cVisibleKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cSiKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cConditionsVisibiliteAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_9_2_0 = (CrossReference)cConditionsVisibiliteAssignment_9_2.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_9_2_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_9_2_0.eContents().get(1);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_9_3_1_0 = (CrossReference)cConditionsVisibiliteAssignment_9_3_1.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_9_3_1_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_9_3_1_0.eContents().get(1);
		
		//PNJ:
		//	name=ID 'situe' 'en' lieu=[Lieu] 'et' 'dialogue' '{' dialogue+=Dialogue* '}' ('visible' 'si'
		//	conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'situe' 'en' lieu=[Lieu] 'et' 'dialogue' '{' dialogue+=Dialogue* '}' ('visible' 'si'
		//conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'situe'
		public Keyword getSitueKeyword_1() { return cSitueKeyword_1; }
		
		//'en'
		public Keyword getEnKeyword_2() { return cEnKeyword_2; }
		
		//lieu=[Lieu]
		public Assignment getLieuAssignment_3() { return cLieuAssignment_3; }
		
		//[Lieu]
		public CrossReference getLieuLieuCrossReference_3_0() { return cLieuLieuCrossReference_3_0; }
		
		//ID
		public RuleCall getLieuLieuIDTerminalRuleCall_3_0_1() { return cLieuLieuIDTerminalRuleCall_3_0_1; }
		
		//'et'
		public Keyword getEtKeyword_4() { return cEtKeyword_4; }
		
		//'dialogue'
		public Keyword getDialogueKeyword_5() { return cDialogueKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//dialogue+=Dialogue*
		public Assignment getDialogueAssignment_7() { return cDialogueAssignment_7; }
		
		//Dialogue
		public RuleCall getDialogueDialogueParserRuleCall_7_0() { return cDialogueDialogueParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'visible'
		public Keyword getVisibleKeyword_9_0() { return cVisibleKeyword_9_0; }
		
		//'si'
		public Keyword getSiKeyword_9_1() { return cSiKeyword_9_1; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_9_2() { return cConditionsVisibiliteAssignment_9_2; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_9_2_0() { return cConditionsVisibiliteConditionCrossReference_9_2_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_9_2_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_9_2_0_1; }
		
		//(',' conditionsVisibilite+=[Condition])*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//','
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_9_3_1() { return cConditionsVisibiliteAssignment_9_3_1; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_9_3_1_0() { return cConditionsVisibiliteConditionCrossReference_9_3_1_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_9_3_1_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_9_3_1_0_1; }
	}
	public class LieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Lieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEstKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeTypePlaceEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cContientKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cPNJsKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cPnjsAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cPnjsPNJParserRuleCall_3_1_1_0 = (RuleCall)cPnjsAssignment_3_1_1.eContents().get(0);
		private final Group cGroup_3_1_2 = (Group)cGroup_3_1.eContents().get(2);
		private final Keyword cCommaKeyword_3_1_2_0 = (Keyword)cGroup_3_1_2.eContents().get(0);
		private final Assignment cPnjsAssignment_3_1_2_1 = (Assignment)cGroup_3_1_2.eContents().get(1);
		private final RuleCall cPnjsPNJParserRuleCall_3_1_2_1_0 = (RuleCall)cPnjsAssignment_3_1_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_1_3 = (Keyword)cGroup_3_1.eContents().get(3);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cObjetsKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cObjetsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cObjetsObjetTenuParserRuleCall_3_2_1_0 = (RuleCall)cObjetsAssignment_3_2_1.eContents().get(0);
		private final Group cGroup_3_2_2 = (Group)cGroup_3_2.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_2_0 = (Keyword)cGroup_3_2_2.eContents().get(0);
		private final Assignment cObjetsAssignment_3_2_2_1 = (Assignment)cGroup_3_2_2.eContents().get(1);
		private final RuleCall cObjetsObjetTenuParserRuleCall_3_2_2_1_0 = (RuleCall)cObjetsAssignment_3_2_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2_3 = (Keyword)cGroup_3_2.eContents().get(3);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cConnaissancesKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cConnaissancesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cConnaissancesConnaissanceCrossReference_3_3_1_0 = (CrossReference)cConnaissancesAssignment_3_3_1.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_3_3_1_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_3_3_1_0.eContents().get(1);
		private final Group cGroup_3_3_2 = (Group)cGroup_3_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_3_2_0 = (Keyword)cGroup_3_3_2.eContents().get(0);
		private final Assignment cConnaissancesAssignment_3_3_2_1 = (Assignment)cGroup_3_3_2.eContents().get(1);
		private final CrossReference cConnaissancesConnaissanceCrossReference_3_3_2_1_0 = (CrossReference)cConnaissancesAssignment_3_3_2_1.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_3_3_2_1_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_3_3_2_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_3_3_3 = (Keyword)cGroup_3_3.eContents().get(3);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		
		//Lieu:
		//	name=ID 'est' type=typePlace ('contient (' ('PNJs:' pnjs+=PNJ (',' pnjs+=PNJ)* ';')? ('objets:' objets+=ObjetTenu (','
		//	objets+=ObjetTenu)* ';')? ('connaissances:' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])* ';')?
		//	')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'est' type=typePlace ('contient (' ('PNJs:' pnjs+=PNJ (',' pnjs+=PNJ)* ';')? ('objets:' objets+=ObjetTenu (','
		//objets+=ObjetTenu)* ';')? ('connaissances:' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])* ';')?
		//')')?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'est'
		public Keyword getEstKeyword_1() { return cEstKeyword_1; }
		
		//type=typePlace
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//typePlace
		public RuleCall getTypeTypePlaceEnumRuleCall_2_0() { return cTypeTypePlaceEnumRuleCall_2_0; }
		
		//('contient (' ('PNJs:' pnjs+=PNJ (',' pnjs+=PNJ)* ';')? ('objets:' objets+=ObjetTenu (',' objets+=ObjetTenu)* ';')?
		//('connaissances:' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])* ';')? ')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'contient ('
		public Keyword getContientKeyword_3_0() { return cContientKeyword_3_0; }
		
		//('PNJs:' pnjs+=PNJ (',' pnjs+=PNJ)* ';')?
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'PNJs:'
		public Keyword getPNJsKeyword_3_1_0() { return cPNJsKeyword_3_1_0; }
		
		//pnjs+=PNJ
		public Assignment getPnjsAssignment_3_1_1() { return cPnjsAssignment_3_1_1; }
		
		//PNJ
		public RuleCall getPnjsPNJParserRuleCall_3_1_1_0() { return cPnjsPNJParserRuleCall_3_1_1_0; }
		
		//(',' pnjs+=PNJ)*
		public Group getGroup_3_1_2() { return cGroup_3_1_2; }
		
		//','
		public Keyword getCommaKeyword_3_1_2_0() { return cCommaKeyword_3_1_2_0; }
		
		//pnjs+=PNJ
		public Assignment getPnjsAssignment_3_1_2_1() { return cPnjsAssignment_3_1_2_1; }
		
		//PNJ
		public RuleCall getPnjsPNJParserRuleCall_3_1_2_1_0() { return cPnjsPNJParserRuleCall_3_1_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_1_3() { return cSemicolonKeyword_3_1_3; }
		
		//('objets:' objets+=ObjetTenu (',' objets+=ObjetTenu)* ';')?
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//'objets:'
		public Keyword getObjetsKeyword_3_2_0() { return cObjetsKeyword_3_2_0; }
		
		//objets+=ObjetTenu
		public Assignment getObjetsAssignment_3_2_1() { return cObjetsAssignment_3_2_1; }
		
		//ObjetTenu
		public RuleCall getObjetsObjetTenuParserRuleCall_3_2_1_0() { return cObjetsObjetTenuParserRuleCall_3_2_1_0; }
		
		//(',' objets+=ObjetTenu)*
		public Group getGroup_3_2_2() { return cGroup_3_2_2; }
		
		//','
		public Keyword getCommaKeyword_3_2_2_0() { return cCommaKeyword_3_2_2_0; }
		
		//objets+=ObjetTenu
		public Assignment getObjetsAssignment_3_2_2_1() { return cObjetsAssignment_3_2_2_1; }
		
		//ObjetTenu
		public RuleCall getObjetsObjetTenuParserRuleCall_3_2_2_1_0() { return cObjetsObjetTenuParserRuleCall_3_2_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_2_3() { return cSemicolonKeyword_3_2_3; }
		
		//('connaissances:' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])* ';')?
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//'connaissances:'
		public Keyword getConnaissancesKeyword_3_3_0() { return cConnaissancesKeyword_3_3_0; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_3_3_1() { return cConnaissancesAssignment_3_3_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_3_3_1_0() { return cConnaissancesConnaissanceCrossReference_3_3_1_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_3_3_1_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_3_3_1_0_1; }
		
		//(',' connaissances+=[Connaissance])*
		public Group getGroup_3_3_2() { return cGroup_3_3_2; }
		
		//','
		public Keyword getCommaKeyword_3_3_2_0() { return cCommaKeyword_3_3_2_0; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_3_3_2_1() { return cConnaissancesAssignment_3_3_2_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_3_3_2_1_0() { return cConnaissancesConnaissanceCrossReference_3_3_2_1_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_3_3_2_1_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_3_3_2_1_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_3_3_3() { return cSemicolonKeyword_3_3_3; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }
	}
	public class DialogueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Dialogue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTexteAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTexteSTRINGTerminalRuleCall_0_0 = (RuleCall)cTexteAssignment_0.eContents().get(0);
		private final Keyword cProposeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cReponsesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cReponsesChoixParserRuleCall_3_0 = (RuleCall)cReponsesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cVisibleKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cSiKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cConditionsVisibiliteAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_5_2_0 = (CrossReference)cConditionsVisibiliteAssignment_5_2.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_5_2_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_5_3_1_0 = (CrossReference)cConditionsVisibiliteAssignment_5_3_1.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_5_3_1_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_5_3_1_0.eContents().get(1);
		
		//Dialogue:
		//	texte=STRING 'propose' '{' reponses+=Choix* '}' ('visible' 'si' conditionsVisibilite+=[Condition] (','
		//	conditionsVisibilite+=[Condition])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//texte=STRING 'propose' '{' reponses+=Choix* '}' ('visible' 'si' conditionsVisibilite+=[Condition] (','
		//conditionsVisibilite+=[Condition])*)?
		public Group getGroup() { return cGroup; }
		
		//texte=STRING
		public Assignment getTexteAssignment_0() { return cTexteAssignment_0; }
		
		//STRING
		public RuleCall getTexteSTRINGTerminalRuleCall_0_0() { return cTexteSTRINGTerminalRuleCall_0_0; }
		
		//'propose'
		public Keyword getProposeKeyword_1() { return cProposeKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//reponses+=Choix*
		public Assignment getReponsesAssignment_3() { return cReponsesAssignment_3; }
		
		//Choix
		public RuleCall getReponsesChoixParserRuleCall_3_0() { return cReponsesChoixParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
		
		//('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'visible'
		public Keyword getVisibleKeyword_5_0() { return cVisibleKeyword_5_0; }
		
		//'si'
		public Keyword getSiKeyword_5_1() { return cSiKeyword_5_1; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_5_2() { return cConditionsVisibiliteAssignment_5_2; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_5_2_0() { return cConditionsVisibiliteConditionCrossReference_5_2_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_5_2_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_5_2_0_1; }
		
		//(',' conditionsVisibilite+=[Condition])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//','
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_5_3_1() { return cConditionsVisibiliteAssignment_5_3_1; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_5_3_1_0() { return cConditionsVisibiliteConditionCrossReference_5_3_1_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_5_3_1_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_5_3_1_0_1; }
	}
	public class ChoixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Choix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTexteAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTexteSTRINGTerminalRuleCall_0_0 = (RuleCall)cTexteAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cImpliqueKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cActionsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cActionsActionCrossReference_1_1_0 = (CrossReference)cActionsAssignment_1_1.eContents().get(0);
		private final RuleCall cActionsActionIDTerminalRuleCall_1_1_0_1 = (RuleCall)cActionsActionCrossReference_1_1_0.eContents().get(1);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cActionsAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final CrossReference cActionsActionCrossReference_1_2_1_0 = (CrossReference)cActionsAssignment_1_2_1.eContents().get(0);
		private final RuleCall cActionsActionIDTerminalRuleCall_1_2_1_0_1 = (RuleCall)cActionsActionCrossReference_1_2_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cVisibleKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cSiKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cConditionsVisibiliteAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_2_2_0 = (CrossReference)cConditionsVisibiliteAssignment_2_2.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_2_2_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_2_2_0.eContents().get(1);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_2_3_1_0 = (CrossReference)cConditionsVisibiliteAssignment_2_3_1.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_2_3_1_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_2_3_1_0.eContents().get(1);
		
		//Choix:
		//	texte=STRING ('implique' actions+=[Action] (',' actions+=[Action])*)? ('visible' 'si'
		//	conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//texte=STRING ('implique' actions+=[Action] (',' actions+=[Action])*)? ('visible' 'si' conditionsVisibilite+=[Condition]
		//(',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup() { return cGroup; }
		
		//texte=STRING
		public Assignment getTexteAssignment_0() { return cTexteAssignment_0; }
		
		//STRING
		public RuleCall getTexteSTRINGTerminalRuleCall_0_0() { return cTexteSTRINGTerminalRuleCall_0_0; }
		
		//('implique' actions+=[Action] (',' actions+=[Action])*)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'implique'
		public Keyword getImpliqueKeyword_1_0() { return cImpliqueKeyword_1_0; }
		
		//actions+=[Action]
		public Assignment getActionsAssignment_1_1() { return cActionsAssignment_1_1; }
		
		//[Action]
		public CrossReference getActionsActionCrossReference_1_1_0() { return cActionsActionCrossReference_1_1_0; }
		
		//ID
		public RuleCall getActionsActionIDTerminalRuleCall_1_1_0_1() { return cActionsActionIDTerminalRuleCall_1_1_0_1; }
		
		//(',' actions+=[Action])*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//actions+=[Action]
		public Assignment getActionsAssignment_1_2_1() { return cActionsAssignment_1_2_1; }
		
		//[Action]
		public CrossReference getActionsActionCrossReference_1_2_1_0() { return cActionsActionCrossReference_1_2_1_0; }
		
		//ID
		public RuleCall getActionsActionIDTerminalRuleCall_1_2_1_0_1() { return cActionsActionIDTerminalRuleCall_1_2_1_0_1; }
		
		//('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'visible'
		public Keyword getVisibleKeyword_2_0() { return cVisibleKeyword_2_0; }
		
		//'si'
		public Keyword getSiKeyword_2_1() { return cSiKeyword_2_1; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_2_2() { return cConditionsVisibiliteAssignment_2_2; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_2_2_0() { return cConditionsVisibiliteConditionCrossReference_2_2_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_2_2_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_2_2_0_1; }
		
		//(',' conditionsVisibilite+=[Condition])*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//','
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_2_3_1() { return cConditionsVisibiliteAssignment_2_3_1; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_2_3_1_0() { return cConditionsVisibiliteConditionCrossReference_2_3_1_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_2_3_1_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_2_3_1_0_1; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cConsommeKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cObjetsConsommesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cObjetsConsommesObjetTenuParserRuleCall_1_1_0 = (RuleCall)cObjetsConsommesAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cObjetsConsommesAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cObjetsConsommesObjetTenuParserRuleCall_1_2_1_0 = (RuleCall)cObjetsConsommesAssignment_1_2_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cDonneKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cObjetsKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cObjetDonnesAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cObjetDonnesObjetTenuParserRuleCall_2_2_1_0 = (RuleCall)cObjetDonnesAssignment_2_2_1.eContents().get(0);
		private final Group cGroup_2_2_2 = (Group)cGroup_2_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_2_0 = (Keyword)cGroup_2_2_2.eContents().get(0);
		private final Assignment cObjetsDonnesAssignment_2_2_2_1 = (Assignment)cGroup_2_2_2.eContents().get(1);
		private final RuleCall cObjetsDonnesObjetTenuParserRuleCall_2_2_2_1_0 = (RuleCall)cObjetsDonnesAssignment_2_2_2_1.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cConnaissancesKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cConnaissancesAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final CrossReference cConnaissancesConnaissanceCrossReference_2_3_1_0 = (CrossReference)cConnaissancesAssignment_2_3_1.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_2_3_1_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_2_3_1_0.eContents().get(1);
		private final Group cGroup_2_3_2 = (Group)cGroup_2_3.eContents().get(2);
		private final Keyword cCommaKeyword_2_3_2_0 = (Keyword)cGroup_2_3_2.eContents().get(0);
		private final Assignment cConnaissancesAssignment_2_3_2_1 = (Assignment)cGroup_2_3_2.eContents().get(1);
		private final CrossReference cConnaissancesConnaissanceCrossReference_2_3_2_1_0 = (CrossReference)cConnaissancesAssignment_2_3_2_1.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_2_3_2_1_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_2_3_2_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//Action:
		//	name=ID ('consomme' objetsConsommes+=ObjetTenu (',' objetsConsommes+=ObjetTenu)*)? ('donne' '(' ('objets:'
		//	ObjetDonnes+=ObjetTenu (',' objetsDonnes+=ObjetTenu)*)? ('connaissances:' connaissances+=[Connaissance] (','
		//	connaissances+=[Connaissance])*)? ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('consomme' objetsConsommes+=ObjetTenu (',' objetsConsommes+=ObjetTenu)*)? ('donne' '(' ('objets:'
		//ObjetDonnes+=ObjetTenu (',' objetsDonnes+=ObjetTenu)*)? ('connaissances:' connaissances+=[Connaissance] (','
		//connaissances+=[Connaissance])*)? ')')?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('consomme' objetsConsommes+=ObjetTenu (',' objetsConsommes+=ObjetTenu)*)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'consomme'
		public Keyword getConsommeKeyword_1_0() { return cConsommeKeyword_1_0; }
		
		//objetsConsommes+=ObjetTenu
		public Assignment getObjetsConsommesAssignment_1_1() { return cObjetsConsommesAssignment_1_1; }
		
		//ObjetTenu
		public RuleCall getObjetsConsommesObjetTenuParserRuleCall_1_1_0() { return cObjetsConsommesObjetTenuParserRuleCall_1_1_0; }
		
		//(',' objetsConsommes+=ObjetTenu)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//objetsConsommes+=ObjetTenu
		public Assignment getObjetsConsommesAssignment_1_2_1() { return cObjetsConsommesAssignment_1_2_1; }
		
		//ObjetTenu
		public RuleCall getObjetsConsommesObjetTenuParserRuleCall_1_2_1_0() { return cObjetsConsommesObjetTenuParserRuleCall_1_2_1_0; }
		
		//('donne' '(' ('objets:' ObjetDonnes+=ObjetTenu (',' objetsDonnes+=ObjetTenu)*)? ('connaissances:'
		//connaissances+=[Connaissance] (',' connaissances+=[Connaissance])*)? ')')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'donne'
		public Keyword getDonneKeyword_2_0() { return cDonneKeyword_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1() { return cLeftParenthesisKeyword_2_1; }
		
		//('objets:' ObjetDonnes+=ObjetTenu (',' objetsDonnes+=ObjetTenu)*)?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'objets:'
		public Keyword getObjetsKeyword_2_2_0() { return cObjetsKeyword_2_2_0; }
		
		//ObjetDonnes+=ObjetTenu
		public Assignment getObjetDonnesAssignment_2_2_1() { return cObjetDonnesAssignment_2_2_1; }
		
		//ObjetTenu
		public RuleCall getObjetDonnesObjetTenuParserRuleCall_2_2_1_0() { return cObjetDonnesObjetTenuParserRuleCall_2_2_1_0; }
		
		//(',' objetsDonnes+=ObjetTenu)*
		public Group getGroup_2_2_2() { return cGroup_2_2_2; }
		
		//','
		public Keyword getCommaKeyword_2_2_2_0() { return cCommaKeyword_2_2_2_0; }
		
		//objetsDonnes+=ObjetTenu
		public Assignment getObjetsDonnesAssignment_2_2_2_1() { return cObjetsDonnesAssignment_2_2_2_1; }
		
		//ObjetTenu
		public RuleCall getObjetsDonnesObjetTenuParserRuleCall_2_2_2_1_0() { return cObjetsDonnesObjetTenuParserRuleCall_2_2_2_1_0; }
		
		//('connaissances:' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])*)?
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'connaissances:'
		public Keyword getConnaissancesKeyword_2_3_0() { return cConnaissancesKeyword_2_3_0; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_2_3_1() { return cConnaissancesAssignment_2_3_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_2_3_1_0() { return cConnaissancesConnaissanceCrossReference_2_3_1_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_2_3_1_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_2_3_1_0_1; }
		
		//(',' connaissances+=[Connaissance])*
		public Group getGroup_2_3_2() { return cGroup_2_3_2; }
		
		//','
		public Keyword getCommaKeyword_2_3_2_0() { return cCommaKeyword_2_3_2_0; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_2_3_2_1() { return cConnaissancesAssignment_2_3_2_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_2_3_2_1_0() { return cConnaissancesConnaissanceCrossReference_2_3_2_1_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_2_3_2_1_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_2_3_2_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_4() { return cRightParenthesisKeyword_2_4; }
	}
	public class CheminElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Chemin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDepuisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLieu1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cLieu1LieuCrossReference_1_0 = (CrossReference)cLieu1Assignment_1.eContents().get(0);
		private final RuleCall cLieu1LieuIDTerminalRuleCall_1_0_1 = (RuleCall)cLieu1LieuCrossReference_1_0.eContents().get(1);
		private final Keyword cJusquKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLieu2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cLieu2LieuCrossReference_3_0 = (CrossReference)cLieu2Assignment_3.eContents().get(0);
		private final RuleCall cLieu2LieuIDTerminalRuleCall_3_0_1 = (RuleCall)cLieu2LieuCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cImpliqueKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cActionsActionCrossReference_4_1_0 = (CrossReference)cActionsAssignment_4_1.eContents().get(0);
		private final RuleCall cActionsActionIDTerminalRuleCall_4_1_0_1 = (RuleCall)cActionsActionCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cActionsAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final CrossReference cActionsActionCrossReference_4_2_1_0 = (CrossReference)cActionsAssignment_4_2_1.eContents().get(0);
		private final RuleCall cActionsActionIDTerminalRuleCall_4_2_1_0_1 = (RuleCall)cActionsActionCrossReference_4_2_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOuvertKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cSiKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cConditionsOuvertureAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cConditionsOuvertureConditionCrossReference_5_2_0 = (CrossReference)cConditionsOuvertureAssignment_5_2.eContents().get(0);
		private final RuleCall cConditionsOuvertureConditionIDTerminalRuleCall_5_2_0_1 = (RuleCall)cConditionsOuvertureConditionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cConditionsOuvertureAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cConditionsOuvertureConditionCrossReference_5_3_1_0 = (CrossReference)cConditionsOuvertureAssignment_5_3_1.eContents().get(0);
		private final RuleCall cConditionsOuvertureConditionIDTerminalRuleCall_5_3_1_0_1 = (RuleCall)cConditionsOuvertureConditionCrossReference_5_3_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVisibleKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cSiKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cConditionsVisibiliteAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_6_2_0 = (CrossReference)cConditionsVisibiliteAssignment_6_2.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_6_2_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cConditionsVisibiliteAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cConditionsVisibiliteConditionCrossReference_6_3_1_0 = (CrossReference)cConditionsVisibiliteAssignment_6_3_1.eContents().get(0);
		private final RuleCall cConditionsVisibiliteConditionIDTerminalRuleCall_6_3_1_0_1 = (RuleCall)cConditionsVisibiliteConditionCrossReference_6_3_1_0.eContents().get(1);
		
		//Chemin:
		//	'depuis' lieu1=[Lieu] 'jusqu\'à' lieu2=[Lieu] ('implique' actions+=[Action] (',' actions+=[Action])*)? ('ouvert' 'si'
		//	conditionsOuverture+=[Condition] (',' conditionsOuverture+=[Condition])*)? ('visible' 'si'
		//	conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'depuis' lieu1=[Lieu] 'jusqu\'à' lieu2=[Lieu] ('implique' actions+=[Action] (',' actions+=[Action])*)? ('ouvert' 'si'
		//conditionsOuverture+=[Condition] (',' conditionsOuverture+=[Condition])*)? ('visible' 'si'
		//conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup() { return cGroup; }
		
		//'depuis'
		public Keyword getDepuisKeyword_0() { return cDepuisKeyword_0; }
		
		//lieu1=[Lieu]
		public Assignment getLieu1Assignment_1() { return cLieu1Assignment_1; }
		
		//[Lieu]
		public CrossReference getLieu1LieuCrossReference_1_0() { return cLieu1LieuCrossReference_1_0; }
		
		//ID
		public RuleCall getLieu1LieuIDTerminalRuleCall_1_0_1() { return cLieu1LieuIDTerminalRuleCall_1_0_1; }
		
		//'jusqu\'à'
		public Keyword getJusquKeyword_2() { return cJusquKeyword_2; }
		
		//lieu2=[Lieu]
		public Assignment getLieu2Assignment_3() { return cLieu2Assignment_3; }
		
		//[Lieu]
		public CrossReference getLieu2LieuCrossReference_3_0() { return cLieu2LieuCrossReference_3_0; }
		
		//ID
		public RuleCall getLieu2LieuIDTerminalRuleCall_3_0_1() { return cLieu2LieuIDTerminalRuleCall_3_0_1; }
		
		//('implique' actions+=[Action] (',' actions+=[Action])*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'implique'
		public Keyword getImpliqueKeyword_4_0() { return cImpliqueKeyword_4_0; }
		
		//actions+=[Action]
		public Assignment getActionsAssignment_4_1() { return cActionsAssignment_4_1; }
		
		//[Action]
		public CrossReference getActionsActionCrossReference_4_1_0() { return cActionsActionCrossReference_4_1_0; }
		
		//ID
		public RuleCall getActionsActionIDTerminalRuleCall_4_1_0_1() { return cActionsActionIDTerminalRuleCall_4_1_0_1; }
		
		//(',' actions+=[Action])*
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//','
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }
		
		//actions+=[Action]
		public Assignment getActionsAssignment_4_2_1() { return cActionsAssignment_4_2_1; }
		
		//[Action]
		public CrossReference getActionsActionCrossReference_4_2_1_0() { return cActionsActionCrossReference_4_2_1_0; }
		
		//ID
		public RuleCall getActionsActionIDTerminalRuleCall_4_2_1_0_1() { return cActionsActionIDTerminalRuleCall_4_2_1_0_1; }
		
		//('ouvert' 'si' conditionsOuverture+=[Condition] (',' conditionsOuverture+=[Condition])*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ouvert'
		public Keyword getOuvertKeyword_5_0() { return cOuvertKeyword_5_0; }
		
		//'si'
		public Keyword getSiKeyword_5_1() { return cSiKeyword_5_1; }
		
		//conditionsOuverture+=[Condition]
		public Assignment getConditionsOuvertureAssignment_5_2() { return cConditionsOuvertureAssignment_5_2; }
		
		//[Condition]
		public CrossReference getConditionsOuvertureConditionCrossReference_5_2_0() { return cConditionsOuvertureConditionCrossReference_5_2_0; }
		
		//ID
		public RuleCall getConditionsOuvertureConditionIDTerminalRuleCall_5_2_0_1() { return cConditionsOuvertureConditionIDTerminalRuleCall_5_2_0_1; }
		
		//(',' conditionsOuverture+=[Condition])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//','
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//conditionsOuverture+=[Condition]
		public Assignment getConditionsOuvertureAssignment_5_3_1() { return cConditionsOuvertureAssignment_5_3_1; }
		
		//[Condition]
		public CrossReference getConditionsOuvertureConditionCrossReference_5_3_1_0() { return cConditionsOuvertureConditionCrossReference_5_3_1_0; }
		
		//ID
		public RuleCall getConditionsOuvertureConditionIDTerminalRuleCall_5_3_1_0_1() { return cConditionsOuvertureConditionIDTerminalRuleCall_5_3_1_0_1; }
		
		//('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'visible'
		public Keyword getVisibleKeyword_6_0() { return cVisibleKeyword_6_0; }
		
		//'si'
		public Keyword getSiKeyword_6_1() { return cSiKeyword_6_1; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_6_2() { return cConditionsVisibiliteAssignment_6_2; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_6_2_0() { return cConditionsVisibiliteConditionCrossReference_6_2_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_6_2_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_6_2_0_1; }
		
		//(',' conditionsVisibilite+=[Condition])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//','
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//conditionsVisibilite+=[Condition]
		public Assignment getConditionsVisibiliteAssignment_6_3_1() { return cConditionsVisibiliteAssignment_6_3_1; }
		
		//[Condition]
		public CrossReference getConditionsVisibiliteConditionCrossReference_6_3_1_0() { return cConditionsVisibiliteConditionCrossReference_6_3_1_0; }
		
		//ID
		public RuleCall getConditionsVisibiliteConditionIDTerminalRuleCall_6_3_1_0_1() { return cConditionsVisibiliteConditionIDTerminalRuleCall_6_3_1_0_1; }
	}
	public class ConditionnelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Conditionnel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPNJParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cConnaissanceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cObjetTenuParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCheminParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDialogueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cChoixParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Conditionnel:
		//	PNJ | Connaissance | ObjetTenu | Chemin | Dialogue | Choix;
		@Override public ParserRule getRule() { return rule; }
		
		//PNJ | Connaissance | ObjetTenu | Chemin | Dialogue | Choix
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PNJ
		public RuleCall getPNJParserRuleCall_0() { return cPNJParserRuleCall_0; }
		
		//Connaissance
		public RuleCall getConnaissanceParserRuleCall_1() { return cConnaissanceParserRuleCall_1; }
		
		//ObjetTenu
		public RuleCall getObjetTenuParserRuleCall_2() { return cObjetTenuParserRuleCall_2; }
		
		//Chemin
		public RuleCall getCheminParserRuleCall_3() { return cCheminParserRuleCall_3; }
		
		//Dialogue
		public RuleCall getDialogueParserRuleCall_4() { return cDialogueParserRuleCall_4; }
		
		//Choix
		public RuleCall getChoixParserRuleCall_5() { return cChoixParserRuleCall_5; }
	}
	public class JoueurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.Joueur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cSitueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEnKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLieuAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cLieuLieuCrossReference_3_0 = (CrossReference)cLieuAssignment_3.eContents().get(0);
		private final RuleCall cLieuLieuIDTerminalRuleCall_3_0_1 = (RuleCall)cLieuLieuCrossReference_3_0.eContents().get(1);
		private final Keyword cEtKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cInventaireKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cTailleKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTailleAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTailleINTTerminalRuleCall_7_0 = (RuleCall)cTailleAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommenceKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cAvecKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cInventaireAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cInventaireObjetTenuParserRuleCall_8_2_0 = (RuleCall)cInventaireAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cInventaireAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cInventaireObjetTenuParserRuleCall_8_3_1_0 = (RuleCall)cInventaireAssignment_8_3_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cConnaissancesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cCommenceKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Keyword cAvecKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Assignment cConnaissancesAssignment_9_3 = (Assignment)cGroup_9.eContents().get(3);
		private final CrossReference cConnaissancesConnaissanceCrossReference_9_3_0 = (CrossReference)cConnaissancesAssignment_9_3.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_9_3_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_9_3_0.eContents().get(1);
		private final Group cGroup_9_4 = (Group)cGroup_9.eContents().get(4);
		private final Keyword cCommaKeyword_9_4_0 = (Keyword)cGroup_9_4.eContents().get(0);
		private final Assignment cConnaissancesAssignment_9_4_1 = (Assignment)cGroup_9_4.eContents().get(1);
		private final CrossReference cConnaissancesConnaissanceCrossReference_9_4_1_0 = (CrossReference)cConnaissancesAssignment_9_4_1.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_9_4_1_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_9_4_1_0.eContents().get(1);
		
		//Joueur:
		//	name=ID 'situe' 'en' lieu=[Lieu] 'et' 'inventaire' 'taille' taille=INT ('commence' 'avec' inventaire+=ObjetTenu (','
		//	inventaire+=ObjetTenu)*)? ('connaissances' 'commence' 'avec' connaissances+=[Connaissance] (','
		//	connaissances+=[Connaissance])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'situe' 'en' lieu=[Lieu] 'et' 'inventaire' 'taille' taille=INT ('commence' 'avec' inventaire+=ObjetTenu (','
		//inventaire+=ObjetTenu)*)? ('connaissances' 'commence' 'avec' connaissances+=[Connaissance] (','
		//connaissances+=[Connaissance])*)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'situe'
		public Keyword getSitueKeyword_1() { return cSitueKeyword_1; }
		
		//'en'
		public Keyword getEnKeyword_2() { return cEnKeyword_2; }
		
		//lieu=[Lieu]
		public Assignment getLieuAssignment_3() { return cLieuAssignment_3; }
		
		//[Lieu]
		public CrossReference getLieuLieuCrossReference_3_0() { return cLieuLieuCrossReference_3_0; }
		
		//ID
		public RuleCall getLieuLieuIDTerminalRuleCall_3_0_1() { return cLieuLieuIDTerminalRuleCall_3_0_1; }
		
		//'et'
		public Keyword getEtKeyword_4() { return cEtKeyword_4; }
		
		//'inventaire'
		public Keyword getInventaireKeyword_5() { return cInventaireKeyword_5; }
		
		//'taille'
		public Keyword getTailleKeyword_6() { return cTailleKeyword_6; }
		
		//taille=INT
		public Assignment getTailleAssignment_7() { return cTailleAssignment_7; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_7_0() { return cTailleINTTerminalRuleCall_7_0; }
		
		//('commence' 'avec' inventaire+=ObjetTenu (',' inventaire+=ObjetTenu)*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'commence'
		public Keyword getCommenceKeyword_8_0() { return cCommenceKeyword_8_0; }
		
		//'avec'
		public Keyword getAvecKeyword_8_1() { return cAvecKeyword_8_1; }
		
		//inventaire+=ObjetTenu
		public Assignment getInventaireAssignment_8_2() { return cInventaireAssignment_8_2; }
		
		//ObjetTenu
		public RuleCall getInventaireObjetTenuParserRuleCall_8_2_0() { return cInventaireObjetTenuParserRuleCall_8_2_0; }
		
		//(',' inventaire+=ObjetTenu)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//','
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//inventaire+=ObjetTenu
		public Assignment getInventaireAssignment_8_3_1() { return cInventaireAssignment_8_3_1; }
		
		//ObjetTenu
		public RuleCall getInventaireObjetTenuParserRuleCall_8_3_1_0() { return cInventaireObjetTenuParserRuleCall_8_3_1_0; }
		
		//('connaissances' 'commence' 'avec' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_9_0() { return cConnaissancesKeyword_9_0; }
		
		//'commence'
		public Keyword getCommenceKeyword_9_1() { return cCommenceKeyword_9_1; }
		
		//'avec'
		public Keyword getAvecKeyword_9_2() { return cAvecKeyword_9_2; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_9_3() { return cConnaissancesAssignment_9_3; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_9_3_0() { return cConnaissancesConnaissanceCrossReference_9_3_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_9_3_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_9_3_0_1; }
		
		//(',' connaissances+=[Connaissance])*
		public Group getGroup_9_4() { return cGroup_9_4; }
		
		//','
		public Keyword getCommaKeyword_9_4_0() { return cCommaKeyword_9_4_0; }
		
		//connaissances+=[Connaissance]
		public Assignment getConnaissancesAssignment_9_4_1() { return cConnaissancesAssignment_9_4_1; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_9_4_1_0() { return cConnaissancesConnaissanceCrossReference_9_4_1_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_9_4_1_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_9_4_1_0_1; }
	}
	public class JeuElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.JeuElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cJoueurParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cConditionnelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cConditionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLieuParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cActionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//JeuElement:
		//	Joueur | Conditionnel | Condition | Lieu | Action;
		@Override public ParserRule getRule() { return rule; }
		
		//Joueur | Conditionnel | Condition | Lieu | Action
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Joueur
		public RuleCall getJoueurParserRuleCall_0() { return cJoueurParserRuleCall_0; }
		
		//Conditionnel
		public RuleCall getConditionnelParserRuleCall_1() { return cConditionnelParserRuleCall_1; }
		
		//Condition
		public RuleCall getConditionParserRuleCall_2() { return cConditionParserRuleCall_2; }
		
		//Lieu
		public RuleCall getLieuParserRuleCall_3() { return cLieuParserRuleCall_3; }
		
		//Action
		public RuleCall getActionParserRuleCall_4() { return cActionParserRuleCall_4; }
	}
	
	public class TypePlaceElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.xtext.Game.typePlace");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDebutEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDebutDebutKeyword_0_0 = (Keyword)cDebutEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinFinKeyword_1_0 = (Keyword)cFinEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cIntermediaireEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cIntermediaireIntermediaireKeyword_2_0 = (Keyword)cIntermediaireEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum typePlace:
		//	debut | fin | intermediaire;
		public EnumRule getRule() { return rule; }
		
		//debut | fin | intermediaire
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//debut
		public EnumLiteralDeclaration getDebutEnumLiteralDeclaration_0() { return cDebutEnumLiteralDeclaration_0; }
		
		//'debut'
		public Keyword getDebutDebutKeyword_0_0() { return cDebutDebutKeyword_0_0; }
		
		//fin
		public EnumLiteralDeclaration getFinEnumLiteralDeclaration_1() { return cFinEnumLiteralDeclaration_1; }
		
		//'fin'
		public Keyword getFinFinKeyword_1_0() { return cFinFinKeyword_1_0; }
		
		//intermediaire
		public EnumLiteralDeclaration getIntermediaireEnumLiteralDeclaration_2() { return cIntermediaireEnumLiteralDeclaration_2; }
		
		//'intermediaire'
		public Keyword getIntermediaireIntermediaireKeyword_2_0() { return cIntermediaireIntermediaireKeyword_2_0; }
	}
	
	private final JeuElements pJeu;
	private final ConnaissanceElements pConnaissance;
	private final ObjetElements pObjet;
	private final ObjetTenuElements pObjetTenu;
	private final ConditionElements pCondition;
	private final PNJElements pPNJ;
	private final LieuElements pLieu;
	private final TypePlaceElements eTypePlace;
	private final DialogueElements pDialogue;
	private final ChoixElements pChoix;
	private final ActionElements pAction;
	private final CheminElements pChemin;
	private final ConditionnelElements pConditionnel;
	private final JoueurElements pJoueur;
	private final JeuElementElements pJeuElement;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GameGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pJeu = new JeuElements();
		this.pConnaissance = new ConnaissanceElements();
		this.pObjet = new ObjetElements();
		this.pObjetTenu = new ObjetTenuElements();
		this.pCondition = new ConditionElements();
		this.pPNJ = new PNJElements();
		this.pLieu = new LieuElements();
		this.eTypePlace = new TypePlaceElements();
		this.pDialogue = new DialogueElements();
		this.pChoix = new ChoixElements();
		this.pAction = new ActionElements();
		this.pChemin = new CheminElements();
		this.pConditionnel = new ConditionnelElements();
		this.pJoueur = new JoueurElements();
		this.pJeuElement = new JeuElementElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.xtext.Game".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Jeu:
	//	'jeu' name=ID
	//	'Connaissances' '{'
	//	jeuElements+=Connaissance*
	//	'}'
	//	'Objets' '{'
	//	jeuElements+=Objet*
	//	'}'
	//	'PNJs' '{'
	//	jeuElements+=PNJ*
	//	'}'
	//	'Actions' '{'
	//	jeuElements+=Action*
	//	'}'
	//	'Conditions' '{'
	//	jeuElements+=Condition*
	//	'}'
	//	'Lieux' '{'
	//	jeuElements+=Lieu*
	//	'}'
	//	'Chemins' '{'
	//	jeuElements+=Chemin*
	//	'}'
	//	'Joueur' '{'
	//	jeuElements+=Joueur
	//	'}';
	public JeuElements getJeuAccess() {
		return pJeu;
	}
	
	public ParserRule getJeuRule() {
		return getJeuAccess().getRule();
	}
	
	//Connaissance:
	//	name=ID ('visible' 'si' conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
	public ConnaissanceElements getConnaissanceAccess() {
		return pConnaissance;
	}
	
	public ParserRule getConnaissanceRule() {
		return getConnaissanceAccess().getRule();
	}
	
	//Objet:
	//	'(' name=ID 'taille' taille=INT ')' '*' quantite=INT;
	public ObjetElements getObjetAccess() {
		return pObjet;
	}
	
	public ParserRule getObjetRule() {
		return getObjetAccess().getRule();
	}
	
	//ObjetTenu:
	//	objet=[Objet] '*' quantite=INT ('visible' 'si' conditionsVisibilite+=[Condition] (','
	//	conditionsVisibilite+=[Condition])*)?;
	public ObjetTenuElements getObjetTenuAccess() {
		return pObjetTenu;
	}
	
	public ParserRule getObjetTenuRule() {
		return getObjetTenuAccess().getRule();
	}
	
	//Condition:
	//	name=ID 'est' 'joueur' 'possede' '(' (negation?='pas'? 'objet:' objet=ObjetTenu | negation?='pas'? 'connaissance:'
	//	connaissance=[Connaissance]) ')';
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//PNJ:
	//	name=ID 'situe' 'en' lieu=[Lieu] 'et' 'dialogue' '{' dialogue+=Dialogue* '}' ('visible' 'si'
	//	conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
	public PNJElements getPNJAccess() {
		return pPNJ;
	}
	
	public ParserRule getPNJRule() {
		return getPNJAccess().getRule();
	}
	
	//Lieu:
	//	name=ID 'est' type=typePlace ('contient (' ('PNJs:' pnjs+=PNJ (',' pnjs+=PNJ)* ';')? ('objets:' objets+=ObjetTenu (','
	//	objets+=ObjetTenu)* ';')? ('connaissances:' connaissances+=[Connaissance] (',' connaissances+=[Connaissance])* ';')?
	//	')')?;
	public LieuElements getLieuAccess() {
		return pLieu;
	}
	
	public ParserRule getLieuRule() {
		return getLieuAccess().getRule();
	}
	
	//enum typePlace:
	//	debut | fin | intermediaire;
	public TypePlaceElements getTypePlaceAccess() {
		return eTypePlace;
	}
	
	public EnumRule getTypePlaceRule() {
		return getTypePlaceAccess().getRule();
	}
	
	//Dialogue:
	//	texte=STRING 'propose' '{' reponses+=Choix* '}' ('visible' 'si' conditionsVisibilite+=[Condition] (','
	//	conditionsVisibilite+=[Condition])*)?;
	public DialogueElements getDialogueAccess() {
		return pDialogue;
	}
	
	public ParserRule getDialogueRule() {
		return getDialogueAccess().getRule();
	}
	
	//Choix:
	//	texte=STRING ('implique' actions+=[Action] (',' actions+=[Action])*)? ('visible' 'si'
	//	conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
	public ChoixElements getChoixAccess() {
		return pChoix;
	}
	
	public ParserRule getChoixRule() {
		return getChoixAccess().getRule();
	}
	
	//Action:
	//	name=ID ('consomme' objetsConsommes+=ObjetTenu (',' objetsConsommes+=ObjetTenu)*)? ('donne' '(' ('objets:'
	//	ObjetDonnes+=ObjetTenu (',' objetsDonnes+=ObjetTenu)*)? ('connaissances:' connaissances+=[Connaissance] (','
	//	connaissances+=[Connaissance])*)? ')')?;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//Chemin:
	//	'depuis' lieu1=[Lieu] 'jusqu\'à' lieu2=[Lieu] ('implique' actions+=[Action] (',' actions+=[Action])*)? ('ouvert' 'si'
	//	conditionsOuverture+=[Condition] (',' conditionsOuverture+=[Condition])*)? ('visible' 'si'
	//	conditionsVisibilite+=[Condition] (',' conditionsVisibilite+=[Condition])*)?;
	public CheminElements getCheminAccess() {
		return pChemin;
	}
	
	public ParserRule getCheminRule() {
		return getCheminAccess().getRule();
	}
	
	//Conditionnel:
	//	PNJ | Connaissance | ObjetTenu | Chemin | Dialogue | Choix;
	public ConditionnelElements getConditionnelAccess() {
		return pConditionnel;
	}
	
	public ParserRule getConditionnelRule() {
		return getConditionnelAccess().getRule();
	}
	
	//Joueur:
	//	name=ID 'situe' 'en' lieu=[Lieu] 'et' 'inventaire' 'taille' taille=INT ('commence' 'avec' inventaire+=ObjetTenu (','
	//	inventaire+=ObjetTenu)*)? ('connaissances' 'commence' 'avec' connaissances+=[Connaissance] (','
	//	connaissances+=[Connaissance])*)?;
	public JoueurElements getJoueurAccess() {
		return pJoueur;
	}
	
	public ParserRule getJoueurRule() {
		return getJoueurAccess().getRule();
	}
	
	//JeuElement:
	//	Joueur | Conditionnel | Condition | Lieu | Action;
	public JeuElementElements getJeuElementAccess() {
		return pJeuElement;
	}
	
	public ParserRule getJeuElementRule() {
		return getJeuElementAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
